services:
  - type: web
    name: strava-stats
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install Flask==2.3.2 gunicorn==21.2.0 requests==2.31.0 python-dotenv==1.0.0 pandas==2.0.1 plotly==5.15.0 numpy==1.24.3 Werkzeug==3.0.0 Jinja2==3.1.2 itsdangerous==2.1.2 click==8.1.7 blinker==1.6.2 MarkupSafe==2.1.3
    startCommand: gunicorn src.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REFRESH_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
