services:
  - type: web
    name: strava-stats
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REFRESH_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src/strava-stats-app
